version: '3.8'

services:
  data:  #image name
    build: .
    volumes:
      - .:/django
    ports:
      - 8001:8001
    image: app:django
    container_name: django_container
    command: python3 manage.py runserver 0.0.0.0:8001


  